### ISSUE TITLE
缺少config.yaml

### ISSUE THREAD

**Issue by lutong9527** [Smile-Cats/sakura-comic-flask#1]
config = get_config(env)
 if configs.get(env):
AttributeError: 'NoneType' object has no attribute 'get'
错误提示这个怎么解决？谢谢

**Comment by Smile-Cats** [comment]
config.yaml 文件我已经上传了，你把里面的相关配置信息改成自己的就可以了

**Comment by lutong9527** [comment]
谢谢，幸苦了！！！
