### ISSUE TITLE
debug的一些问题

### ISSUE THREAD

**Issue by lutong9527** [Smile-Cats/sakura-comic-flask#2]
当我运行docker run image_id时提示：
* Environment: production
   WARNING: This is a development server. Do not use it in a production deployment.
   Use a production WSGI server instead.
 * Debug mode: off
Usage: flask run [OPTIONS]
Try 'flask run --help' for help.
Error: Failed to find Flask application or factory in module 'app'. Use 'FLASK_APP=app:name' to specify one.
当我运行gunicorn --config config/gun.conf -D wsgi_gunicorn:app时提示：
WARNING: configuration file should have a valid Python extension.
我的运行环境centos7,宝塔,python3.8各种调试结果还是无法运行。可以发个详细教程吗？谢谢！！！！！

**Comment by Smile-Cats** [comment]
你在服务器上输入这个命令试试：ps -x
看看下面有没有出现类似这个的进程：
<img width="829" alt="1678340651751" src="https://user-images.githubusercontent.com/45654036/223931083-3d783b87-85fd-4225-8ac4-b7f7dc3eeeb1.png">

**Comment by lutong9527** [comment]
config/gun.conf运行提示

将gun.conf改为gun.py能运行,这个是在网上查询的解决办法。centos的Python我也改为python3.8.14了 gunicorn==20.1.0 eventlet==0.30.2




绝望的领港人
***@***.***



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "Smile-Cats/sakura-comic-flask"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2023年3月9日(星期四) 中午1:45
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [Smile-Cats/sakura-comic-flask] debug的一些问题 (Issue #2)





 
你在服务器上输入这个命令试试：ps -x
 看看下面有没有出现类似这个的进程：

**Comment by Smile-Cats** [comment]
我加了wsgi.py文件，现在docker应该是可以直接运行了，你再试试?

**Comment by lutong9527** [comment]
是不是我的运行环境不行啊？都要崩溃了&nbsp; 总是各种错误提示？是不是和宝塔环境不兼容啊？





绝望的领港人
***@***.***



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "Smile-Cats/sakura-comic-flask"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2023年3月9日(星期四) 下午2:32
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [Smile-Cats/sakura-comic-flask] debug的一些问题 (Issue #2)





 
我加了wsgi.py文件，现在docker应该是可以直接运行了，你再试试?

**Comment by Smile-Cats** [comment]
是什么错误提示?

**Comment by lutong9527** [comment]
绝望的领港人
***@***.***



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "Smile-Cats/sakura-comic-flask"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2023年3月9日(星期四) 下午3:31
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [Smile-Cats/sakura-comic-flask] debug的一些问题 (Issue #2)





 
是什么错误提示?

**Comment by Smile-Cats** [comment]
<img width="703" alt="1678351060839" src="https://user-images.githubusercontent.com/45654036/223966444-3dbf08ca-85d0-41d0-ace4-10569f6d0456.png">
我看不到你发的提示

**Comment by lutong9527** [comment]
我运行docker后的错误提示





绝望的领港人
***@***.***



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "Smile-Cats/sakura-comic-flask"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2023年3月9日(星期四) 下午4:46
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [Smile-Cats/sakura-comic-flask] debug的一些问题 (Issue #2)





 

 我看不到你发的提示

**Comment by lutong9527** [comment]
![image](https://user-images.githubusercontent.com/69670240/224240877-87391435-1fae-4463-98e1-ecce603a4595.png)
我运行docker后的错误提示

**Comment by Smile-Cats** [comment]
你这个错误提示截全点，把最下面的那几行截出来

**Comment by lutong9527** [comment]
![image](https://user-images.githubusercontent.com/69670240/224253618-0f88528b-7e61-4a8d-a75d-e1e2b41a431f.png)

**Comment by Smile-Cats** [comment]
看起来是wsgi.py文件中的语法错误，你看看你的wsgi.py文件是对的吗

**Comment by lutong9527** [comment]
我在oracle上运行docker成功了  但是我访问不了5000端口  没有任何数据 也没有提示

**Comment by Smile-Cats** [comment]
你docker运行时得加-p命令执行端口映射

**Comment by lutong9527** [comment]
![image](https://user-images.githubusercontent.com/69670240/224290588-0e538de1-d4b9-4269-80fb-de1a659bf09c.png)
这个提示是什么意思？要把后台文件包和前端的包放一起吗？我是分成两个域名，放在两个文件夹里面的

**Comment by Smile-Cats** [comment]
前端的文件也需要运行的，运行用的是npm，这个是前后端分离的，你前端代码跑通了吗？

**Comment by lutong9527** [comment]
![image](https://user-images.githubusercontent.com/69670240/224462771-3fe325c9-927f-48f9-9268-f8bd1cf7e48c.png)
前端跑起来了

**Comment by Smile-Cats** [comment]
那你在前端跑的机器上，打开浏览器 输入 http://localhost:3000不能打开网页吗

**Comment by lutong9527** [comment]
我用yarn build后域名运行目录设置为dist后，浏览器可以打开。npm run dev运行后，后台显示正常，但是前端访问不了。npm install 提示错误。你打包的npm版本是多少？node版本是多少？

**Comment by Smile-Cats** [comment]
npm 8.11.0，node v16.15.1
