### ISSUE TITLE
老哥，能给一下电影数据吗

### ISSUE THREAD

**Issue by Yesterdaylove** [Smile-Cats/sakura-comic-flask#3]
能给一份电影数据吗

**Comment by Smile-Cats** [comment]
电影数据通过樱花资源网获得，这个是链接，解析下就好了
https://m3u8.apiyhzy.com/api.php/provide/vod/?ac=detail&pg=1

**Comment by Yesterdaylove** [comment]
多谢老哥了



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2023年3月16日(周四) 晚上7:21
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [Smile-Cats/sakura-comic-flask] 老哥，能给一下电影数据吗 (Issue #3)




 
电影数据通过樱花资源网获得，这个是链接，解析下就好了
 https://m3u8.apiyhzy.com/api.php/provide/vod/?ac=detail&amp;pg=1
