### ISSUE TITLE
关于接口

### ISSUE THREAD

**Issue by Mashiroyes** [Smile-Cats/sakura-comic-flask#5]
本人在尝试用java语言实现同一个动漫接口的后端，但是python语言太不熟练了，项目中很多地方看不明白
第一个问题
http://localhost:3000/#/
访问首页时就能看到很多动漫是怎么实现的，项目中并没有看到/这个路径的实现逻辑
第二个问题
vod_list这个接口完全看不懂，访问https://m3u8.apiyhzy.com/api.php/provide/vod/vod_list
得到的json数据如下
![image](https://github.com/Smile-Cats/sakura-comic-flask/assets/59597481/bcf02e41-0655-4843-919c-61ea370f5125)
但是项目中的接口实现却是
@vod_bp.route('/vod_list', methods=['GET'])
def get_vod_list():
    '''
    通过查询条件返回数据
    :return: json
    '''
    page = int(request.args.get('page', 1))  # 查询的页数
    mov_type = int(request.args.get('movtype', 0))  # 视频的类型, 一级类型
    mov_type_list = mov_type_dict.get(mov_type)  # 通过一级类型查询到的视频二级类型
    vod_area = request.args.get('vod_area')  # 查询参数 视频地址
    type_name = request.args.get('vod_class')  # 查询参数 视频二级类型
    vod_year = request.args.get('vod_year')  # 查询参数 视频年份
    keyword = request.args.get('keyword')  # 关键词
    
json数据中并没有vod_year、vod_area这些字段，这些字段都是https://m3u8.apiyhzy.com/api.php/provide/vod/?ac=detail&pg=1接口中的。
请问一下这个接口的作用是什么

**Comment by Smile-Cats** [comment]
是通过爬虫把这些接口的字段读取并保存到数据库中，并非直接通过这些接口访问前端的，你可以看下数据库结构

**Comment by Mashiroyes** [comment]
> 是通过爬虫把这些接口的字段读取并保存到数据库中，并非直接通过这些接口访问前端的，你可以看下数据库结构

请问项目中是通过task.py实现的爬虫吗？

**Comment by Smile-Cats** [comment]
> > 是通过爬虫把这些接口的字段读取并保存到数据库中，并非直接通过这些接口访问前端的，你可以看下数据库结构
> 
> 请问项目中是通过task.py实现的爬虫吗？

是的
